In [ ]:
%matplotlib inline

import pandas as pd # for using pandas daraframe
import numpy as np # for som math operations
from sklearn.preprocessing import StandardScaler # for standardizing the Data

import matplotlib.pyplot as plt # for plotting

In [ ]:
googledata1 = pd.read_csv('/content/data_table_for_daily_case_trends__the_united_states.csv', header=2)
googledata1['Date'] = pd.to_datetime(googledata1['Date'])
df2 = googledata1
start_date = '2021-10-1'
end_date = '2022-10-1'
mask = (df2['Date'] > start_date) & (df2['Date'] <= end_date)
  
df2 = df2.loc[mask]

df2_first = df2.head(n=274)
#df2_first.iloc[::-1]
dft = df2_first[::-1]

display(dft)

State       Date  New Cases  7-Day Moving Avg  Historic Cases
274  United States 2022-01-01     303446            421265               0
273  United States 2022-01-02     417043            449674               0
272  United States 2022-01-03     909487            512789               0
271  United States 2022-01-04     740961            561784               0
270  United States 2022-01-05     718131            594512               0
..             ...        ...        ...               ...             ...
5    United States 2022-09-27      40163             50046               0
4    United States 2022-09-28      63763             47124           11753
3    United States 2022-09-29      89873             45737             621
2    United States 2022-09-30      46383             44698              71
1    United States 2022-10-01       8024             43334               0

[274 rows x 5 columns]

In [ ]:
dfn1 = pd.DataFrame()
l=[]

for count, column in enumerate(dft):    
    # Select column contents by column
    # name using [] operator
    if(count>1):
      columnSeriesObj = dft[column]
      columnSeriesObj[np.isnan(columnSeriesObj)] = 0
      dfn1.insert(count-2, column, columnSeriesObj.tolist(), True)
      l.append(columnSeriesObj.tolist())
      #print('Column Name : ', column)
      #print('Column Contents : ', columnSeriesObj.values)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [ ]:
dfn1.head()

New Cases  7-Day Moving Avg  Historic Cases
0     303446            421265               0
1     417043            449674               0
2     909487            512789               0
3     740961            561784               0
4     718131            594512               0

In [ ]:
X1 = dfn1.values # getting all values as a matrix of dataframe 
sc = StandardScaler() # creating a StandardScaler object
X_std1 = sc.fit_transform(X1) # standardizing the data

In [ ]:
X_std1[:,1]

array([ 1.38308401,  1.53029419,  1.85734444,  2.11122747,  2.28081791,
        2.43793054,  2.72473882,  2.83268639,  2.89072271,  3.15975218,
        3.21528051,  3.32620244,  3.39590304,  3.3901305 ,  3.40930839,
        3.35680624,  3.13670347,  3.17051481,  3.10966476,  3.01420018,
        2.96229912,  2.85851255,  2.78074387,  2.80953404,  2.54084138,
        2.36482031,  2.21453731,  2.02586225,  1.94373048,  1.82603073,
        1.50343684,  1.35571884,  1.17686332,  1.01293142,  0.82189863,
        0.73449177,  0.68913016,  0.48012165,  0.40632224,  0.32564657,
        0.18918865,  0.10529507,  0.07791954,  0.04090583, -0.04863593,
       -0.1151808 , -0.18229566, -0.23214991, -0.27056788, -0.29071996,
       -0.30335841, -0.39675544, -0.39208663, -0.41591779, -0.43504387,
       -0.45661059, -0.46807276, -0.47822394, -0.46093222, -0.51532573,
       -0.53106809, -0.54800226, -0.57183861, -0.58038342, -0.58720269,
       -0.59969086, -0.60851031, -0.61409631, -0.62336139, -0.62

**Symptoms data**

In [ ]:
df = pd.read_csv('/content/2022_country_daily_2022_US_daily_symptoms_dataset.csv', index_col = 0)

In [ ]:
dfu = pd.read_csv('/content/2022_country_daily_2022_US_daily_symptoms_dataset.csv', index_col = 0)
dfu['date'] = pd.to_datetime(dfu['date'])

df_first = dfu.head(n=274)
display(df_first)

In [ ]:
dfn = pd.DataFrame()
l=[]

for count, column in enumerate(df_first):    
    # Select column contents by column
    # name using [] operator
    if(count>8):
      columnSeriesObj = df_first[column]
      columnSeriesObj[np.isnan(columnSeriesObj)] = 0
      dfn.insert(count-9, column, columnSeriesObj.tolist(), True)
      l.append(columnSeriesObj.tolist())
      #print('Column Name : ', column)
      #print('Column Contents : ', columnSeriesObj.values)

In [ ]:
dfn.head()

In [ ]:
for col in dfn.columns:
    print(col)

symptom:Acne
symptom:Actinic keratosis
symptom:Acute bronchitis
symptom:Adrenal crisis
symptom:Ageusia
symptom:Alcoholism
symptom:Allergic conjunctivitis
symptom:Allergy
symptom:Amblyopia
symptom:Amenorrhea
symptom:Amnesia
symptom:Anal fissure
symptom:Anaphylaxis
symptom:Anemia
symptom:Angina pectoris
symptom:Angioedema
symptom:Angular cheilitis
symptom:Anosmia
symptom:Anxiety
symptom:Aphasia
symptom:Aphonia
symptom:Apnea
symptom:Arthralgia
symptom:Arthritis
symptom:Ascites
symptom:Asperger syndrome
symptom:Asphyxia
symptom:Asthma
symptom:Astigmatism
symptom:Ataxia
symptom:Atheroma
symptom:Attention deficit hyperactivity disorder
symptom:Auditory hallucination
symptom:Autoimmune disease
symptom:Avoidant personality disorder
symptom:Back pain
symptom:Bacterial vaginosis
symptom:Balance disorder
symptom:Beau's lines
symptom:Bell's palsy
symptom:Biliary colic
symptom:Binge eating
symptom:Bleeding
symptom:Bleeding on probing
symptom:Blepharospasm
symptom:Bloating
symptom:Blood in stool
sym

In [ ]:
dfn.shape

(274, 420)

**Standardizing the data**

In [ ]:
X = dfn.values # getting all values as a matrix of dataframe 
sc = StandardScaler() # creating a StandardScaler object
X_std = sc.fit_transform(X) # standardizing the data

**Create the reduced binary description**

In [ ]:
rng: np.random.RandomState = np.random.RandomState(0)
rng.randn(4,1) 

array([[1.76405235],
       [0.40015721],
       [0.97873798],
       [2.2408932 ]])

In [ ]:
import numpy as np
    
class Bit_map:

    def __init__(self, reduced_size, inp_size, rng: np.random.RandomState = np.random.RandomState(0)):
        self.reduced_size = reduced_size
        self.inp_size = inp_size

        # take random normal vectors for projection

        self.normals = rng.randn(self.reduced_size, inp_size) 
        
    def generate(self, inp_vector):

        # self.normals.T = create delta normal vectors
        # Take dot product of input vector with each of these normal vectors.
        # If vector and normal on same side, then Binary = 1 else 0

        binary = (np.dot(inp_vector, self.normals.T) > 0).astype('int')
        return binary #''.join(bools.astype('str'))
       
ht = Bit_map(reduced_size=20, inp_size=274)

**Example**

In [ ]:
h_l =[]

for i in range(420):
  h_p=[]
  h_p.append(ht.generate(X_std[:,i]))
  h_l.append(h_p)

In [ ]:
sp2 = ht.generate(X_std1[:,1])
sp2 # CDC Covid data

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0])

In [ ]:
score = []
h_l =[]

for i in range(420):
  h_p=[]
  h_p.append(ht.generate(X_std[:,i]))
  h_l.append(h_p)
  
for i in range(420):
    sp1 = h_l[i] # Symptom data
    a =[i for i, j in zip(sp1[0], sp2) if i == j];
    score.append(len(a)) # How many bits are matching!

In [ ]:
score[314]

17

In [ ]:
top_k = sorted(range(len(score)), key=lambda i: score[i], reverse=True)[:15]
top_k

[17, 2, 4, 57, 73, 82, 90, 111, 139, 174, 209, 238, 263, 307, 314]

In [ ]:
for i,c in enumerate(top_k): #for ele in enumerate(l1):
  print(i,dfn.columns[c],score[c])