In [1]:
%matplotlib inline

import pandas as pd # for using pandas daraframe
import numpy as np # for som math operations
from sklearn.preprocessing import StandardScaler # for standardizing the Data

import matplotlib.pyplot as plt # for plotting

**Testing data**

In [110]:
data2 = pd.read_csv('/content/COVID-19_Diagnostic_Laboratory_Testing__PCR_Testing__Time_Series.csv')

In [111]:
data2['date'] = pd.to_datetime(data2['date'])
df2 = data2
start_date = '2022-1-1'
end_date = '2022-10-1'

mask = (df2['date'] >= start_date) & (df2['date'] <= end_date)

df2 = df2.loc[mask]

In [112]:
state_name = 'Georgia'
mask = (df2['state_name'] == state_name)
df2 = df2.loc[mask]

In [113]:
overall_outcome = 'Negative'
mask = (df2['overall_outcome'] == overall_outcome)
df2 = df2.loc[mask]

In [114]:
dfn1 = pd.DataFrame()
l=[]

for count, column in enumerate(df2):    
    # Select column contents by column
    # name using [] operator
    if((count>5) and (count<7)):
      columnSeriesObj = df2[column]
      columnSeriesObj[np.isnan(columnSeriesObj)] = 0
      dfn1.insert(count-6, column, columnSeriesObj.tolist(), True)
      l.append(columnSeriesObj.tolist())
      #print('Column Name : ', column)
      #print('Column Contents : ', columnSeriesObj.values)

In [115]:
dfn1.head()

new_results_reported
0                 11118
1                 11968
2                 18269
3                 36279
4                 51392

In [116]:
X1 = dfn1.values # getting all values as a matrix of dataframe 
sc = StandardScaler() # creating a StandardScaler object
X_std1 = sc.fit_transform(X1) # standardizing the data

**df2 = 274 x 9**

**Symptoms**

In [117]:
dfu = pd.read_csv('/content/2022_sub_region_1_daily_2022_US_Georgia_daily_symptoms_dataset.csv', index_col = 0)
dfu['date'] = pd.to_datetime(dfu['date'])

df_first = dfu.head(n=274)

In [118]:
dfn = pd.DataFrame()
l=[]

for count, column in enumerate(df_first):    
    # Select column contents by column
    # name using [] operator
    if(count>8):
      columnSeriesObj = df_first[column]
      columnSeriesObj[np.isnan(columnSeriesObj)] = 0
      dfn.insert(count-9, column, columnSeriesObj.tolist(), True)
      l.append(columnSeriesObj.tolist())
      #print('Column Name : ', column)
      #print('Column Contents : ', columnSeriesObj.values)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:8870: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3249: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe

In [119]:
X = dfn.values # getting all values as a matrix of dataframe 
sc = StandardScaler() # creating a StandardScaler object
X_std = sc.fit_transform(X) # standardizing the data

In [120]:
rng: np.random.RandomState = np.random.RandomState(0)
rng.randn(4,1) 

array([[1.76405235],
       [0.40015721],
       [0.97873798],
       [2.2408932 ]])

In [126]:
import numpy as np
    
class Bit_map:

    def __init__(self, reduced_size, inp_size, rng: np.random.RandomState = np.random.RandomState(0)):
        self.reduced_size = reduced_size
        self.inp_size = inp_size

        # take random normal vectors for projection

        self.normals = rng.randn(self.reduced_size, inp_size) 
        
    def generate(self, inp_vector):

        # self.normals.T = create delta normal vectors
        # Take dot product of input vector with each of these normal vectors.
        # If vector and normal on same side, then Binary = 1 else 0

        binary = (np.dot(inp_vector, self.normals.T) > 0).astype('int')
        return binary #''.join(bools.astype('str'))
       
ht = Bit_map(reduced_size=20, inp_size=274)

In [127]:
sp2 = ht.generate(X_std1[:,0])
sp2 # CDC Covid data

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1])

In [128]:
score = []
h_l =[]

for i in range(420):
  h_p=[]
  h_p.append(ht.generate(X_std[:,i]))
  h_l.append(h_p)
  
for i in range(420):
    sp1 = h_l[i] # Symptom data
    a =[i for i, j in zip(sp1[0], sp2) if i == j];
    score.append(len(a)) # How many bits are matching!

In [129]:
top_k = sorted(range(len(score)), key=lambda i: score[i], reverse=True)[:15]
top_k

[340, 394, 14, 114, 168, 196, 205, 264, 271, 294, 306, 349, 364, 368, 412]

In [130]:
for i,c in enumerate(top_k): #for ele in enumerate(l1):
  print(i,dfn.columns[c],score[c])

0 symptom:Scoliosis 16
1 symptom:Urethritis 16
2 symptom:Angina pectoris 15
3 symptom:Dysphagia 15
4 symptom:Heart murmur 15
5 symptom:Hyperthyroidism 15
6 symptom:Hypomania 15
7 symptom:Nasal polyp 15
8 symptom:Neutropenia 15
9 symptom:Pelvic inflammatory disease 15
10 symptom:Pleurisy 15
11 symptom:Shyness 15
12 symptom:Strabismus 15
13 symptom:Stuttering 15
14 symptom:Weakness 15


**Symptoms searches which are causing people to test themselves, but they are not covid positive.**




1.   Dysphagia : Swallowing difficulties
2.   Hypomania : Over-excitment
3.   Heart murmur
4.   Nasal polyp





**Searched and were found positive**

In [102]:
data2 = pd.read_csv('/content/COVID-19_Diagnostic_Laboratory_Testing__PCR_Testing__Time_Series.csv')

data2['date'] = pd.to_datetime(data2['date'])
df2 = data2
start_date = '2022-1-1'
end_date = '2022-10-1'

mask = (df2['date'] >= start_date) & (df2['date'] <= end_date)

df2 = df2.loc[mask]

X = dfn.values # getting all values as a matrix of dataframe 
sc = StandardScaler() # creating a StandardScaler object
X_std = sc.fit_transform(X) # standardizing the data

In [103]:
state_name = 'Georgia'
mask = (df2['state_name'] == state_name)
df2 = df2.loc[mask]

In [104]:
overall_outcome = 'Positive'
mask = (df2['overall_outcome'] == overall_outcome)
df2 = df2.loc[mask]

In [105]:
dfn1 = pd.DataFrame()
l=[]

for count, column in enumerate(df2):    
    # Select column contents by column
    # name using [] operator
    if((count>5) and (count<7)):
      columnSeriesObj = df2[column]
      columnSeriesObj[np.isnan(columnSeriesObj)] = 0
      dfn1.insert(count-6, column, columnSeriesObj.tolist(), True)
      l.append(columnSeriesObj.tolist())
      #print('Column Name : ', column)
      #print('Column Contents : ', columnSeriesObj.values)

X1 = dfn1.values # getting all values as a matrix of dataframe 
sc = StandardScaler() # creating a StandardScaler object
X_std1 = sc.fit_transform(X1) # standardizing the data

In [106]:
sp2 = ht.generate(X_std1[:,0])
sp2 # CDC Covid data

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0])

In [107]:
score = []
h_l =[]

for i in range(420):
  h_p=[]
  h_p.append(ht.generate(X_std[:,i]))
  h_l.append(h_p)
  
for i in range(420):
    sp1 = h_l[i] # Symptom data
    a =[i for i, j in zip(sp1[0], sp2) if i == j];
    score.append(len(a)) # How many bits are matching!

In [108]:
top_k = sorted(range(len(score)), key=lambda i: score[i], reverse=True)[:15]
top_k

[82, 90, 238, 2, 4, 17, 73, 209, 301, 380, 263, 111, 139, 314, 362]

In [109]:
for i,c in enumerate(top_k): #for ele in enumerate(l1):
  print(i,dfn.columns[c],score[c])

0 symptom:Common cold 36
1 symptom:Cough 36
2 symptom:Low-grade fever 36
3 symptom:Acute bronchitis 35
4 symptom:Ageusia 35
5 symptom:Anosmia 35
6 symptom:Chills 35
7 symptom:Hypoxemia 35
8 symptom:Phlegm 35
9 symptom:Throat irritation 35
10 symptom:Nasal congestion 34
11 symptom:Dysgeusia 33
12 symptom:Fever 33
13 symptom:Post-nasal drip 33
14 symptom:Sputum 33
